function PrivacyPolicy() {
  return (
      <div className="flex justify-center">
           <div className="w-3/4">
      <p>PRIVACY POLICY Last Updated: June 15, 2022</p>

<p>Thank you for visiting collegecompass360.com (the &quot;Site&quot;). The Site is an Internet property of Digital Media Solutions (&quot;Company,&quot; &quot;we,&quot; &quot;our&quot; or &quot;us&quot;). This collegecompass360.com Privacy Policy (&quot;Privacy Policy&quot;) covers our treatment of personal information and other information that we collect when an end-user visitor to the Site (&quot;User,&quot; &quot;you&quot; or &quot;your&quot;): (a) accesses or uses the Site; (b) accesses and/or views any of the: (i) links to third-party education-related resources and other information (&quot;Third-Party Links&quot;); and/or (ii) blog posts, text, video and/or other information pertaining to education-related products and/or services made available on the Site (the &quot;Informational Content,&quot; and together with the Third-Party Links, the &quot;Content&quot;); (c) accesses the comments sections associated with the blog posts and/or other interactive features made available on the Site (&quot;Interactive Services&quot;); and/or (d) utilizes the various contact forms and/or contact information made available on the Site as a means to contact directly, or request to be contacted by, Company and/or Company's third-party product and/or service providers and online aggregators (&quot;Third-Party Service Providers&quot;) (collectively, the &quot;Contact Services,&quot; and together with the Site, Content and Interactive Services, the &quot;Site Offerings&quot;).</p>

<p>Users with disabilities who wish to access this Privacy Policy in an alternative format can contact us by calling us at: (800) 719-5930; emailing us at: support@collegecompass360.com or sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States.</p>

<p>Capitalized terms not defined herein shall have the meanings set forth in the collegecompass360.com Website Terms and Conditions (&quot;Terms and Conditions&quot;). IF YOU DO NOT AGREE TO TERMS OF THIS PRIVACY POLICY IN THEIR ENTIRETY, YOU MAY NOT ACCESS OR OTHERWISE USE THE SITE OFFERINGS.</p>

<p>Your California Privacy Rights Shine the Light. If you are a resident of the State of California and would like to learn how your &ldquo;personal information&rdquo; (as defined in the Shine the Light Law, Cal. Civ. Code &sect; 1798.83) is shared with third-parties, what categories of personal information we have shared with third-parties in the preceding year, as well as the names and addresses of those third-parties, please e-mail us at: support@collegecompass360.com; send mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States; or call us at: 800-719-5930.</p>

<p>Further, if you are a resident of the State of California and would like to opt-out from the disclosure of your personal information to any third-party for marketing purposes, please e-mail us at: support@collegecompass360.com; send mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States; or call us at: 800-719-5930. Please be advised that where California State residents opt-out from permitting their personal information to be shared, such individuals may still receive selected offers directly from us, in accordance with applicable law.</p>

<p>California Consumer Privacy Act of 2018 (&ldquo;CCPA&rdquo;). In addition to the foregoing, if you are a resident of the State of California, certain other privacy-related rights may apply to you in accordance with the CCPA, including the right to opt-out of our sale of your personal information, as well as the right to know what personal information about you we have collected, whether your personal information was shared with third-parties in the preceding year and, if so, what categories of personal information were shared, as well as the categories of third-parties with whom we ahared that personal information. Please see our Provisions for California Residents below for a more complete description of your rights under the CCPA as a California State resident.</p>

<p>Privacy Policy Quick Links Below are links to key sections of our Privacy Policy:</p>

<p>Your Nevada Privacy Rights Personal Information Collected Use and Sharing of Personal Information Non-Personal Information Collection and Use Your California Privacy Rights Security of Your PersonalInformation Opt-Out/Unsubscribe Deleting, Modifying and Updating Your Information Children&rsquo;s Privacy Changes to this Privacy Policy Contact Us Your Nevada Privacy Rights If you are a resident of the State of Nevada and would like to opt-out from the sale of your personal information to any third party data broker, please e-mail us at: please e-mail us at: support@collegecompass360.com; call us at: (800) 719-5930; or send us mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States.</p>

<p>Personal Information Collected Please see our Provisions for California Residents below for additional details regarding the categories of personal information collected. For the purposes of this Privacy Policy, &quot;personal information&quot; shall mean individually identifiable information from or about an individual. We collect personal information when you access certain of the Site Offerings and complete the required information request form and/or otherwise provide such information to us. Where a User attempts to utilize the Contact Services, that User may be required to submit, and Company may collect, some or all of the following information: (a) the User's e-mail address; (b) the User's full name; (c) the User's telephone number; (d) certain information pertaining to User's education needs; and (e) any other information collected via the Contact Services form.</p>

<p>Upon entering Contact Data and clicking on the applicable submission button on the Site: (i) Company may pass your Contact Data along to one (1) or more of its marketing partners and/or affiliates (collectively, &quot;Marketing Partners&quot;) or Third-Party Service Providers; (ii) you may be contacted by Company and/or one (1) or more of its Marketing Partners or Third-Party Service Providers regarding your request; and/or (iii) you may be contacted by one (1) or more Marketing Partners with third-party offers that Company feels may be of interest to you. Where Company contacts you in connection with your submission of Contact Data, a Company representative may request additional information over the telephone including some or all of the following: (A) User date of birth; (B) User mailing address; (C) certain information pertaining to the User's education needs; and (D) any other information requested by the applicable Company representative.</p>

<p>We may also obtain information, including personal information, about you from third party sources that track end-user activity on third party websites.</p>

<p>Use Of Personal Information Please see our Provisions for California Residents below for details regarding our uses of personal information.</p>

<p>By submitting your personal information by and through the Site Offerings, you agree that we may share, sell, rent, lease or otherwise provide that personal information to any third-party for any purpose permitted by law, and we may work with other businesses to bring selected third-party offers to you. These businesses and third-parties may include, but are not limited to: (a) providers of direct marketing services and applications, including lookup and reference, data enhancement, suppression and validation; (b) e-mail marketers; (c) telemarketers (where permitted by applicable law); and (d) internet, mobile and e-mail marketers. We may also use your personal information to send you promotional messages regarding various Company products and/or services, as well as third-party products and/or services that we think may be of interest to you.</p>

<p>Without limiting the foregoing, with your permission, we may share your User Data with those Third-Party Service Providers that you request to be contacted by. These Third-Party Service Providers may use your User Data to offer you education-related products and/or services, and for any other lawful purposes, subject to any restrictions contained herein. The information that you supply directly to any Third-Party Service Provider shall be governed by the applicable Third-Party Service Provider's privacy policy. Where you submit personal information, we use the personal information that you make available to personalize your experience with the Site and to facilitate the delivery of the applicable Site Offerings to you, including to respond to any inquiries made by you.</p>

<p>We may also provide your information to third-party companies and individuals to perform certain functions on our behalf. Examples include sending direct and electronic mail, removing duplicate information from User lists, analyzing data and providing marketing analysis. The agents performing these limited functions on our behalf shall have access to our Users' personal information as needed to perform these functions for us, but we do not permit them to use User personal information for other purposes.</p>

<p>We will also use your personal information with your permission, for customer service, to provide you with information that you may request, to customize your experience with the Site Offerings and/or to contact you when necessary in connection with your use of the Site Offerings. We may also use your personal information for internal business purposes, such as analyzing and managing our service offerings including, without limitation, the Site Offerings. We may also combine the information we have gathered about you with information from other sources.</p>

<p>By submitting your personal information by and through the Site Offerings, and thereby providing your permission, you agree that such act constitutes an inquiry and/or application for purposes of the Amended Telemarketing Sales Rule (16 CFR &sect;310 et seq.), as amended from time to time (the &quot;Rule&quot;) and applicable state do-not-call regulations. As such, notwithstanding that your telephone number may be listed on the Federal Trade Commission's Do-Not-Call List, and/or on applicable state do-not-call lists, we retain the right to contact you via telemarketing in accordance with the Rule and applicable state do-not-call regulations.</p>

<p>Where you provide &quot;prior express consent&quot; within the meaning of the Telephone Consumer Protection Act (47 USC &sect; 227), and its implementing regulations adopted by the Federal Communications Commission (47 CFR &sect; 64.1200), as amended from time-to-time (&quot;TCPA&quot;), you consent to receive telephone calls from Company and/or its designated Third-Party Service Provider(s), including artificial voice calls, pre-recorded messages and/or calls (including SMS text messages) delivered via automated technology, to the telephone number(s) that you provided. Please note that you are not required to provide this consent in order to obtain access to the Site Offerings, and your consent simply allows Company and its designated Third-Party Service Providers, as applicable, to contact you via these means.</p>

<p>Please be advised that by agreeing to this Privacy Policy, you are obligated to immediately inform us if and when the telephone number that you have previously provided to us changes. Without limiting the foregoing, if you: (i) have your telephone number reassigned to another person or entity; (ii) give up your telephone number so that it is no longer used by you; (iii) port your telephone number to a landline or vice versa; or (iv) otherwise stop using that telephone number for any reason (collectively &quot;Phone Number Change&quot;), you agree that you shall promptly notify Company of the Phone Number Change via e-mail at: support@collegecompass360.com, or by using one of the methods set forth in the &quot;Contact Us&quot; section below.</p>

<p>We reserve the right to release current or past personal information: (A) in the event that we believe that the Site Offerings are being or have been used in violation of the Terms and Conditions or to commit unlawful acts; (B) if the information is subpoenaed; provided, however, that, where permitted by applicable law, we shall provide you with e-mail notice, and opportunity to challenge the subpoena, prior to disclosure of any personal information pursuant to a subpoena; or (C) if we are sold, merge with a third-party, are acquired or are the subject of bankruptcy proceedings; provided, however, that if Company is involved in a bankruptcy proceeding, merger, acquisition or sale of all or a portion of its assets, you will be notified via email and/or a prominent notice on the Site of any change in ownership or uses of your personal information, as well as any choices that you may have regarding your personal information.</p>

<p>You hereby consent to the disclosure of any record or communication to any third-party when we, in our sole discretion, determine the disclosure to be appropriate including, without limitation, sharing your e-mail address with third-parties for suppression purposes in compliance with applicable law, including the CAN-SPAM Act of 2003, as amended from time to time. Users should also be aware that courts of equity, such as U.S. Bankruptcy Courts, might have the authority under certain circumstances to permit personal information to be shared or transferred to third-parties without permission.</p>

<p>Non-Personal Information Collection And Use Please see our Provisions for California Residents below for more details regarding the categories and types of non-personal information collected</p>

<p>IP Addresses/Browser Type We may collect certain non-personally identifiable information about you and your desktop computer and/or mobile device when you visit many of the pages of the Site. This non-personally identifiable information includes, without limitation, the type of browser that you use (e.g., Safari, Chrome, Internet Explorer), your IP address, the type of operating system that you use (e.g., Windows or iOS) and the domain name of your Internet service provider (e.g., Verizon, AT&amp;T). We use the non-personally identifiable information that we collect to improve the design and content of the Site Offerings and to enable us to personalize your Internet experience. We also may use this information in the aggregate to analyze usage of the Site Offerings.</p>

<p>Cookies When a User visits the Site, we send one (1) or more cookies and/or gif files (collectively, &quot;Cookies&quot;) to assign an anonymous, unique identifier to the applicable User's computer. A Cookie is a piece of data stored on your hard drive containing non-personally identifiable information about you. Cookies have many benefits to enhance your experience at the Site. To find out more about Cookies, please visit www.cookiecentral.com. We use Cookies to improve the quality of the Site Offerings, including for storing User preferences and tracking Site-User trends (such as pages opened and length of stay at the Site).</p>

<p>Most Internet browsers are initially set up to accept Cookies, but you can reset your browser to refuse all Cookies or to indicate when a Cookie is being sent. To disable and reject certain Cookies, follow the instructions associated with your Internet browser. Even in the case where a User rejects a Cookie, he or she may still use the Site Offerings; provided, however, that certain functions of the Site Offerings may be impaired or rendered inoperable if the use of Cookies is disabled. We reserve the right to retain Cookie data indefinitely.</p>

<p>Company reserves the right to transfer and/or sell aggregate, hashed and/or group data about Users of the Site Offerings for lawful purposes. Aggregate or group data is data that describes the demographics, usage and other characteristics of Site Offerings Users as a group, without disclosing personally identifiable information.</p>

<p>Behavioral Tracking/Advertising  Company, as well as third party entities such as Google&reg;, use Cookies, pixels and other tracking technology (collectively, &quot;Tracking Technology&quot;) in connection with the Site for purposes of tracking Users' activities (such as websites visited, advertisements selected and pages viewed) after they leave the Site. Company, and its third-party partners, use this Tracking Technology to target applicable Users with advertisements featuring Company products and/or services, as well as third-party products and/or services, that may be of interest to applicable Users.</p>

<p>Without limiting the foregoing, Company utilizes the third party services of Lead Intelligence, Inc. d/b/a Jornaya (&ldquo;Jornaya&rdquo;) and ActiveProspect, Inc. (including its TrustedForm service) to record Site visits from Users, track the Site activity of such Users and to confirm, among other things, that User &quot;prior express consent&quot; has been provided as required by the TCPA. For further details, please see Jornaya&rsquo;s privacy policy by clicking here and/or Active Prospect, Inc.&rsquo;s privacy policy by clicking here.</p>

<p>In addition, Company uses a third party service called Hotjar in order to better understand our Users' needs and to optimize the Company Offerings. Hotjar is a technology service that helps us better understand our Users' Site-related experience (e.g. how much time they spend on which Site pages, which links they choose to click on, what Users do and do not like, etc.) and this enables us to build and maintain our Company Offerings with User feedback. Hotjar uses cookies and other technology to collect data on our Users' behavior and their devices (in particular, the various devices' IP addresses (captured and stored only in anonymized form), device screen size, device type (unique device identifiers), browser information, geographic location (country only) and preferred language used to display our website). Hotjar stores this information in a pseudonymized User profile. Neither Hotjar nor Company will ever use this information to identify individual Users or to match this information with additional data on an individual User. For further details, please see Hotjar's privacy policy by clicking on this link.</p>

<p>In general, Users may be able to disable some, or all, of this tracking activity by utilizing the &quot;Do Not Track&quot; setting or similar options within most major Internet browsers. In addition, Users may be able to opt-out of this form of tracking utilizing the options made available by the Network Advertising Initiative or Digital Advertising Alliance.</p>

<p>You can opt-out from the creation of a User profile, Hotjar's storing of data about your usage of the Site and Hotjar's use of tracking cookies on other websites by following this opt-out link.</p>

<p>Further, Users can opt-out of certain Google&reg;-related tracking technology, and customize the Google&reg; Display Network ads that they receive, by visiting the Google&reg; Ads Settings at: http://www.google.com/settings/ads. Google&reg; also recommends installing the Google&reg; Analytics Opt-out Browser Add-on for your web browser, which is available here: https://tools.google.com/dlpage/gaoptout. To the greatest extent permissible under applicable law, we are not responsible for the tracking practices of third-parties in connection with the Site.</p>

<p>Google&reg; is a registered trademark of Google, Inc. (&quot;Google&quot;). Please be advised that Company is not in any way affiliated with Google, nor are the Site Offerings endorsed, administered or sponsored by Google.</p>

<p>Interactive Services  If you engage in any interaction with Company, other Users or any third-party via the Interactive Services, you should be aware that the personal information that you submit by and through the Interactive Services can be read, collected and/or used by other Users of these services, and could be used to send you unsolicited messages or otherwise to contact you without your consent or desire. We are not responsible for the personal information that you choose to submit via the Interactive Services.</p>

<p>Third-Party Websites This Site may contain links to third-party owned and/or operated websites including, without limitation, websites owned and/or operated by Company's Third-Party Service Providers and/or Marketing Partners. Company is not responsible for the privacy practices or the content of such entities and/or websites. In some cases, you may be able to make a purchase through one of these third-party websites. In these instances, you may be required to provide certain information, such as a credit card number, to register or complete a transaction at such website. These third-party websites and entities have separate privacy and data collection practices and Company has no responsibility or liability relating to them.</p>

<p>Security We endeavor to safeguard and protect our Users' personal information. When Users make personal information available to us, their personal information is protected both online and offline (to the extent that we maintain any personal information offline). Where our registration/application process prompts Users to enter sensitive information (such as financial information, medical information, driver's license/ID card number, health insurance information, data collected from an automated license plate recognition system or Social Security Number), and when we store and transmit such sensitive information, that information is encrypted with advanced TLS (Transport Layer Security).</p>

<p>Access to your personal information is strictly limited, and we take reasonable measures to ensure that your personal information is not accessible to the public. All of our Users' personal information is restricted in our offices, as well as the offices of our third-party service providers. Only employees or third-party agents who need User personal information to perform a specific job are granted access to User personal information. Our employees are dedicated to ensuring the security and privacy of all User personal information. Employees not adhering to our firm policies are subject to disciplinary action. The servers that we store User personal information on are kept in a secure physical environment. We also have security measures in place to protect the loss, misuse and alteration of personal information under our control.</p>

<p>Please be advised, however, that while we take every reasonable precaution available to protect your data, no storage facility, technology, software, security protocols or data transmission over the Internet or via wireless networks can be guaranteed to be 100% secure. Computer hackers that circumvent our security measures may gain access to certain portions of your personal information, and technological bugs, errors and glitches may cause inadvertent disclosures of your personal information; provided, however, that any attempt to breach the security of the network, our servers, databases or other hardware or software may constitute a crime punishable by law. For the reasons mentioned above, we cannot warrant that your personal information will be absolutely secure. Any transmission of data at or through the Site, other Site Offerings or otherwise via the Internet or wireless networks, is done at your own risk.</p>

<p>In compliance with applicable federal and state laws, we shall notify you and any applicable regulatory agencies in the event that we learn of an information security breach with respect to your personal information. You will be notified via e-mail in the event of such a breach. Please be advised that notice may be delayed in order to address the needs of law enforcement, determine the scope of network damage, and to engage in remedial measures.</p>

<p>Minors Please see our Provisions for California Residents below for more details regarding the personal information of minors. Visitors under eighteen (18) years of age are not permitted to use and/or submit their personal information at the Site. Company does not knowingly solicit or collect information from visitors under eighteen (18) years of age. Company encourages parents and guardians to spend time online with their children and to participate and monitor the interactive activities of their children.</p>

<p>Opt-Out/Unsubscribe Please see our Provisions for California Residents below for instructions on how California Residents can opt-out of the sale of their personal information to third parties. To opt-out of receiving e-mail and other forms of communications from us, you can: (a) follow the instructions included in the applicable e-mail message or other communication; or (b) e-mail us at: support@collegecompass360.com.</p>

<p>Notwithstanding the foregoing, we may continue to contact you for the purpose of communicating information relating to your request for Site Offerings, as well as to respond to any inquiry or request made by you. To opt-out of receiving Site Offerings-related and/or inquiry response-related messages from Company, you must cease requesting and/or utilizing the Site Offerings and/or cease submitting inquiries to Company, as applicable.</p>

<p>Deleting, Modifying And Updating Your Information Please see our Provisions for California Residents below for instructions on how California Residents can access and/or delete personal information that we have collected. At your request, we will: (a) inform you of what personal information we have on file for you; (b) amend the personal information that we have on file for you; and/or (c) remove personal information that you have provided to us, or that we have collected. You may do so by e-mailing us at: support@collegecompass360.com. We ask individual Users to identify themselves and the information requested to be accessed, corrected or removed before processing such requests, and, to the extent permitted by applicable law, we may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others or would be extremely impractical (for instance, requests concerning information residing on backup tapes).</p>

<p>Please be advised that deleting your personal information may terminate your access to certain of the Site Offerings. If you wish to continue using the full complement of Site Offerings, you may not be able to delete all of the personal information that we have on file for you.</p>

<p>Please be further advised that, after you delete your personal information, residual copies may take a period of time before they are deleted from our active servers and may remain in our backup systems.</p>

<p>Transfer of Personal Information Internationally If you are visiting the Site from a country other than the country in which our servers are located, your communications with us may result in the transfer of information across international boundaries. By visiting the Site and/or otherwise communicating electronically with us, you consent to such transfers. Even if your jurisdiction does not have the same privacy laws as the jurisdiction where our servers are located, we will treat your information as subject to the protections described in this Privacy Policy.</p>

<p>Changes To This Privacy Policy Company reserves the right to change or update this Privacy Policy at any time by posting a notice on the Site that we are changing our Privacy Policy. If the manner in which we use personal information changes, Company will notify Users by: (a) sending the modified policy to our Users via email; and/or (b) by any other reasonable means acceptable under applicable state and federal law. You will have a choice as to whether or not we use your information in this different manner and we will only use your information in this different manner where you opt-in to such use.</p>

<p>Contact Us If you have any questions about this Privacy Policy or our privacy practices in general, you may email us as at: support@collegecompass360.com; call us at: (800) 719-5930; or send us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States.</p>

<p>Filing a Complaint with the Federal Trade Commission</p>

<p>To file a complaint regarding our privacy practices, please Click Here.</p>

<p>Provisions For California Residents These Provisions for California Residents (&quot;Provisions&quot;) supplement, and do not limit in any way, the Privacy Policy set forth above. These Provisions apply solely to residents of the State of California (&quot;CA Users&quot;). We adopt these Provisions in compliance with the California Consumer Privacy Act of 2018 (&quot;CCPA&rdquo;), the California Privacy Rights Act of 2020 (&ldquo;CPRA&rdquo;) and other applicable California State privacy laws. Any terms defined in the CCPA or CPRA have the same meaning when used in these Provisions. Users with disabilities who wish to access these Provisions in an alternative format can contact us by calling us at: (800) 719-5930; emailing us at: support@collegecompass360.com; or sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States.</p>

<p>Categories of Information We Collect We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular CA User or device (&quot;personal information&quot;). In particular, we have collected the following categories of personal information from CA Users within the last twelve (12) months:</p>

<p>Category Examples Collected A. Identifiers. A real name, alias, postal address, unique personal identifier, online identifier, Internet Protocol address, email address, account name, telephone number, or other similar identifiers. YES B. Personal information categories listed in the California Customer Records statute (Cal. Civ. Code &sect; 1798.80(e)). A name, signature, Social Security number, physical characteristics or description, postal address, telephone number, passport number, driver's license or State identification card number, insurance policy number, education, employment, employment history, bank account number, credit card number, debit card number, or any other financial information, medical information, or health insurance information. Some personal information included in this category may overlap with other categories. YES C. Protected classification characteristics under California or federal law. Age (40 years or older), race, color, ancestry, national origin, citizenship, religion or creed, marital status, medical condition, physical or mental disability, sex (including gender, gender identity, gender expression, pregnancy or childbirth and related medical conditions), sexual orientation, veteran or military status, genetic information (including familial genetic information). YES F. Internet or other similar network activity. Browsing history, search history, information on a User's interaction with a website, application or advertisement. YES I. Professional or employment-related information. Current or past job history or performance evaluations. YES Sensitive Personal Information (Cal. Civ. Code &sect;1798.140(ae)). A Social Security number, driver&rsquo;s license number, state identification card number, or passport number. Account log-in information, financial account, or debit or credit card number used in combination with any required security code, access code, password, or log-in credentials necessary to access an account. Precise geolocation, racial or ethnic origin, religious or philosophical beliefs, or union membership. The contents of a consumer&rsquo;s U.S. mail, electronic mail, or text messages unless the business is the intended recipient, and a consumer&rsquo;s genetic data. NO Personal information does not include:</p>

<p>Publicly available information from government records. &bull; Information that we believe has been lawfully made public by the consumer or from widely distributed media or from disclosure to a third party by the consumer where the consumer did not limit disclosure to a specific audience. De-identified or aggregated User information. Information excluded from the scope of the CCPA and CPRA, such as: health or medical information covered by the Health Insurance Portability and Accountability Act of 1996 (HIPAA) and the California Confidentiality of Medical Information Act (CMIA) or clinical trial data; personal information covered by certain sector-specific privacy laws, including the Fair Credit Reporting Act (FRCA), the Gramm-Leach-Bliley Act (GLBA), the California Financial Information Privacy Act (FIPA), and the Driver's Privacy Protection Act of 1994. We obtain the categories of personal information for which we indicated &quot;YES&quot; above from the following categories of sources (with the specific categories of personal information indicated in parenthesis).</p>

<p>Directly from our CA Users. For example, from online registration forms that our CA Users submit to us related to the products and/or services that we offer by and through the Site. (Category A, B, C and I) Indirectly from our CA Users. For example, through information we collect from our CA Users in the course of providing our products and/or services to them. (Category A, B, C, F and I) Directly and indirectly from activity on the Site. This includes the type of browser that you use (e.g., Safari, Chrome, Internet Explorer), your IP address, the type of operating system that you use (e.g., Windows or iOS) and the domain name of your Internet Service Provider. In addition, we obtain certain Site usage details and analytics as same are collected automatically by us and our third party partners, such as Google&reg; and Hotjar&reg;. (Category F) When our CA Users interact with us on our social media accounts, including commenting on and/or liking our posts. (Category F) Directly from CA Users via online registration forms that our CA Users submit to us in order to enter a promotion or sweepstakes featured on the Site. (Category A, B, C and I)  From third-parties that interact with us in connection with the products and/or services that we offer to our CA Users. For example, third party entities that assist us in sending direct and electronic mail, removing duplicate information from CA User lists, analyzing data and providing marketing analysis. (Category A, B, C and I) From third-party data brokers or aggregators. (Category A, B, C and I)  From third-party websites that employ tracking technology that tracks User visits and browsing activity. (Category A, B, C and I) From publicly availably sources, such as Internet search engines. (Category A, B, C and I) Use of Personal Information We may use or disclose the personal information that we collect (including the following specific items of personal information: (a) e-mail address; (b) full name; (c) telephone number; and (d) certain information pertaining to CA User education needs) for one or more of the following business purposes (with the specific categories of personal information indicated in parenthesis). For example, if you provide us with personal information in connection with your request for a price quote and/or other information regarding the education-related products and/or services featured on the Site, we will use that personal information to better provide you with the requested quote/information. (Category A, B, C and I)</p>

<p>To provide you with information, products or services that you request from us. (Category A, B, C, F and I) To create, maintain, customize and secure your account with us. (Category A, B, C and I) To enable you to enter a sweepstakes or promotion featured on the Site. (Category A, B, C and I) To provide you with e-mail, direct mail and telemarketing messages concerning certain Company products and/or services, as well as third-party products and/or services, that we believe may be of interest to you. (Category A, B, C, F and I) To deliver relevant Site content and advertisements to you and measure or understand the effectiveness of the advertising we serve to you. (Category A, B, C, F and I) To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including the Site's Terms and Conditions. (Category A, B, C, F and I) To improve the Site and better present its contents to you. (Category A, B, C, F and I) For customer service purposes and to respond to inquiries from you. (Category A, B, C and I) For testing, research, analysis and product development. (Category A, B, C, F and I) As necessary or appropriate to protect our rights, property or safety, and that of our clients or others. (Category A, B, C, F and I) To respond to law enforcement requests and as required by applicable law, court order, or governmental regulations. (Category A, B, C, F and I) As described to you when collecting your personal information or as otherwise set forth in the CCPA. (Category A, B, C, F and I) To evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation or similar proceeding, in which personal information held by us is among the assets transferred. (Category A, B, C, F and I) We will not collect additional categories of personal information or use the personal information we collected for materially different, unrelated or incompatible purposes without providing you with notice.</p>

<p>Retention of Personal Information and Sensitive Personal Information We retain all categories of your personal information and sensitive personal information that we collect for a period of 10 years. We may also use certain criteria to determine whether and when to delete certain categories of collected personal and sensitive personal information including:</p>

<p>Date of collection. Frequency of consumer interaction with us. Last interaction the consumer had with us. Whether the purpose of collection has been completed. Sharing Personal Information Subject to your right to opt-out of such sharing/sale, we may share, rent and/or sell your personal information with/to third parties for marketing purposes, as well as other business purposes. The specific items of personal information that we may sell include: (a) e-mail address; (b) full name; (c) telephone number; and (d) certain information pertaining to CA User education needs. When we disclose personal information to a third party service provider or other entity, we enter into a contractual relationship that describes the purpose for which such third party may use the personal information and requires that third party to both keep the personal information confidential and not use it for any purpose other than the performance of its services under the applicable contract. Please note, we do not collect information from CA Users that we actually know are less than eighteen (18) years of age and we do not share or sell the personal information of CA Users that we actually know are less than eighteen (18) years of age. Without limiting the foregoing, we have not shared or sold the personal information of CA Users that we actually know are less than sixteen (16) years of age in the preceding twelve (12) months.</p>

<p>In the preceding twelve (12) months, we have disclosed the following categories of personal information for a business purpose:</p>

<p>Category A Identifiers. Category B California Customer Records personal information categories. Category C Protected classification characteristics under California or federal law. Category F Internet or other similar network activity. Category I Professional or employment-related information. In the preceding twelve (12) months, we have sold the following categories of personal information to third parties:</p>

<p>Category A Identifiers. Category B California Customer Records personal information categories. Category C Protected classification characteristics under California or federal law. Category F Internet or other similar network activity. Category I Professional or employment-related information. We disclose your personal information from Category A, B and F for a business purpose to the following categories of third parties (with the specific categories of personal information indicated in parenthesisOur affiliates. (Category A, B, C, F and I)</p>

<p>Service providers. (Category A, B, C, F and I) Third parties who provide the education-related products and/or services featured on the Site. (Category A, B, C, F and I) Third parties who purchase and/or license your personal information for marketing purposes, including: (a) providers of direct marketing services and applications, including lookup and reference, data enhancement, suppression and validation; (b) e-mail marketers; (c) telemarketers (where permitted by applicable law); and (d) direct marketers. (Category A, B, C, F and I)  Third parties to whom you authorize us to disclose your personal information in connection with the products and/or services that we provide to you. (Category A, B, C, F and I) In the preceding twelve (12) months, we have: (a) sold personal information (including (i) e-mail address; (ii) full name; (iii) telephone number; and (iv) certain marketing information to the third parties who purchase and/or license your personal information for marketing purposes, as well as the third parties who provide products and/or services featured on the Site; and (b) shared your personal information for the business purposes set forth above.</p>

<p>In the preceding twelve (12) months, we have:</p>

<p>Received 989 requests for access to specific information and to exercise data portability rights. We have complied with 989 of those requests (in whole or in part) and denied 0 requests. The median number of days within which we substantively responded to such requests was 0; Received 1958 requests to delete personal information. We have complied with 1958 of those requests (in whole or in part) and denied 0 requests. The median number of days within which we substantively responded to such requests was 0; and Received 3616 requests to opt-out from the sale of personal information. We have complied with 0 of those requests (in whole or in part) and denied 3616 requests. The median number of days within which we substantively responded to such requests was 0. Your Rights and Choices The CCPA provides California residents (CA Users) with specific rights regarding their personal information. This section describes your CCPA rights and explains how to exercise those rights.</p>

<p>Opt-Out from the Sale of Your Personal Information You have the right to opt-out of our sale of your personal information to third parties. To exercise your right to opt-out of our sale of your personal information to third parties, please submit a verifiable CA User request to us by either:</p>

<p>Clicking here Calling us at: (800) 290-4010 Emailing us at: ConsumerInquiries@collegecompass360.com; or Sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States. Where you make a request to opt-out of the sale of your personal information through an Authorized Agent, we will require that you or the Authorized Agent provide us with a valid written authorization executed by you and that Authorized Agent, with the validity of such document determined by us in our reasonable, good faith discretion. Please submit such documentation to us by emailing us at: ConsumerInquiries@collegecompass360.com; or sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States.</p>

<p>We endeavor to act on all opt-out requests as soon as practicable, but in all cases within fifteen (15) days of the receipt of your request.</p>

<p>Opt-Out from the Sharing of Your Personal Information You have the right to opt-out of our sharing your personal information with third parties. To exercise your right to opt-out of our sharing your personal information with third parties, please submit a verifiable CA User request to us by either:</p>

<p>Clicking here Calling us at: (800) 290-4010 Emailing us at: ConsumerInquiries@collegecompass360.com; or Sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States. We endeavor to act on all opt-out requests as soon as practicable, but in all cases within fifteen (15) business days of the receipt of your request.</p>

<p>Opt-Out from the Use and/or Sharing of Your Sensitive Personal Information You have the right to limit our use of your sensitive personal information, including any sensitive information from Category B (California Customer Records personal information), Category C (Protected classification characteristics under California or federal law) and/or Category I (Professional or employment-related information), to those uses which: (i) are necessary to perform the services or provide the goods requested by you; (ii) help us to ensure security and integrity of your personal information to the extent the use of your sensitive personal information is reasonably necessary and proportionate for these purposes; (iii) are short-term, transient uses including, but not limited to, non-personalized advertising shown as part of your then-current interaction with the Site, provided that your personal information is not disclosed to another third party and is not used to build a profile about you or otherwise alter your experience outside the then-current interaction with the Site; (iv) involve performing services on behalf of Company, including maintaining or servicing accounts, providing customer service, processing or fulfilling orders and transactions, verifying customer information, processing payments, providing financing, providing analytic services, providing storage, or providing similar services on behalf of Company; and (v) include activities to verify or maintain the quality or safety of a service or device that is owned, manufactured, manufactured for, or controlled by, Company, and to improve, upgrade, or enhance the service or device that is owned, manufactured, manufactured for, or controlled by, Company.</p>

<p>You also have the right opt-out of our sharing your sensitive personal information with third parties, including any sensitive information from Category B (California Customer Records personal information), Category C (Protected classification characteristics under California or federal law) and/or Category I (Professional or employment-related information).</p>

<p>To exercise your right to limit our use of your sensitive personal information and/or opt-out of our sharing your sensitive personal information with third parties, please submit a verifiable CA User request to us by either:</p>

<p>Clicking here Calling us at: (800) 290-4010 Emailing us at: ConsumerInquiries@collegecompass360.com; or Sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States. We endeavor to act on all such requests as soon as practicable, but in all cases within fifteen (15) business days of the receipt of your request.</p>

<p>Access to Specific Information and Data Portability Rights You have the right to request that we disclose certain information to you about our collection and use of your personal information over the past twelve (12) months. Once we receive and confirm your verifiable CA User request, we will disclose to you:</p>

<p>The categories of personal information we collected about you. The categories of sources for the personal information we collected about you. Our business or commercial purpose for collecting or selling that personal information. The categories of third parties with whom we have shared that personal information. The specific pieces of personal information we collected about you (also called a data portability request). If we sold or disclosed your personal information for a business purpose, two separate lists disclosing: sales, identifying the personal information categories that each category of recipient purchased; and disclosures for a business purpose, identifying the personal information categories that each category of recipient obtained. Deletion Request Rights You have the right to request that we delete any of your personal information that we collected from you and retained, subject to certain exceptions. Once we receive and confirm your verifiable CA User request, we will delete (and direct our service providers to delete) your personal information from our (their) records, unless an exception applies.</p>

<p>We may deny your deletion request if retaining the information is necessary for us or our service providers to:</p>

<p>Complete the transaction for which we collected the personal information, provide a good or service that you requested, take actions reasonably anticipated within the context of our ongoing business relationship with you, or otherwise perform our obligations in connection with our contract with you. Detect security incidents, protect against malicious, deceptive, fraudulent or illegal activity, or prosecute those responsible for such activities. Debug products to identify and repair errors that impair existing intended functionality. Exercise free speech rights, ensure the right of another CA User to exercise their free speech rights or exercise another right provided for by law. Comply with the California Electronic Communications Privacy Act (Cal. Penal Code &sect; 1546 seq.). Engage in public or peer-reviewed scientific, historical, or statistical research in the public interest that adheres to all other applicable ethics and privacy laws, when the information's deletion may likely render impossible or seriously impair the research's achievement, if you previously provided informed consent. Enable solely internal uses that are reasonably aligned with CA User expectations based on your relationship with us. Comply with a legal obligation. Make other internal and lawful uses of that information that are compatible with the context in which you provided it. Exercising Access, Data Portability and Deletion Rights To exercise your access, data portability and/or deletion rights described above, please submit a verifiable CA User request to us by either:</p>

<p>Clicking here Calling us at: (800) 290-4010 Emailing us at: ConsumerInquiries@collegecompass360.com; or Sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States. Only you or a person registered with the California Secretary of State that you authorize to act on your behalf, may make a verifiable CA User request related to your personal information. Where you make a data deletion request, data portability request and/or information access request through an authorized agent, we will require that you or the authorized agent provide us with a valid written authorization executed by both parties, with the validity of such document determined by us in our reasonable, good faith discretion. Please submit such documentation to us by emailing us at: ConsumerInquiries@collegecompass360.com or sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States</p>

<p>You may only make a verifiable CA User request for access or data portability twice within a 12-month period. The verifiable CA User request must:</p>

<p>Provide sufficient information that allows us to reasonably verify that you are the person about whom we collected personal information or an authorized representative. Describe your request with sufficient detail that allows us to properly understand, evaluate, and respond to it. We cannot respond to your request or provide you with personal information if we cannot verify your identity or authority to make the request and confirm that the personal information relates to you. Making a verifiable CA User request does not require you to create an account with us. We will only use personal information provided in a verifiable CA User request to verify the requestor's identity or authority to make the request.</p>

<p>Response Timing and Format We endeavor to respond to all verifiable CA User requests within forty-five (45) days of the receipt thereof. If we require more time (up to ninety (90) days), we will inform you of the reason and extension period in writing. We will deliver our written response by mail or electronically, at your option. Any disclosures we provide will only cover the twelve (12) month period preceding the receipt of your verifiable request. The response we provide will also explain the reasons we cannot comply with a request, if applicable. For data portability requests, we will select a format to provide your personal information that is readily useable and should allow you to transmit the information from one entity to another entity without hindrance.</p>

<p>We do not charge a fee to process or respond to your verifiable CA User request unless it is excessive, repetitive, or manifestly unfounded. If we determine that the request warrants a fee, we will tell you why we made that decision and provide you with a cost estimate before completing your request.</p>

<p>Non-Discrimination We will not discriminate against you for exercising any of your CCPA rights. Unless permitted by the CCPA, we will not:</p>

<p>Deny you goods or services; Charge you different prices or rates for goods or services, including through granting discounts or other benefits, or imposing penalties; Provide you a different level or quality of goods or services; and/or Suggest that you may receive a different price or rate for goods or services or a different level or quality of goods or services. Changes to these Provisions We reserve the right to amend these Provisions in our discretion and at any time. When we make changes to these Provisions, we will notify you by email or through a notice on the Site's homepage.</p>

<p>Contact Information If you have any questions or comments about these Provisions, the Privacy Policy, the ways in which we collect and use your personal information, your choices and rights regarding such use, or wish to exercise your rights under California law, please do not hesitate to contact us by either:</p>

<p>Calling us at: (800) 290-4010 Emailing us at: ConsumerInquiries@collegecompass360.com; or Sending us U.S. Mail to: 3900 Crown Rd SW #16709, SMB#27993, Atlanta, Georgia 30304, United States.</p>
    </div>
          </div>
  );
}

export default PrivacyPolicy;
